version: "3"

services:
  web:
    image: nlesc/sherlock-demo-site
    volumes:
      - /data/shared/cluster-analysis/data/combined:/usr/share/nginx/html/webdata
    depends_on:
      - deeplearning-viz
    ports:
      - "80:80"


  deeplearning-viz:
    image: nlesc/sherlock-deeplearning-viz
    ports:
      - "3000:3000"


        #        timeline:

        #          image: nlesc/timeline

        #        swarm-viz:
        #exports port 8080
        #          image: manomarks/visualizer

        #          volumes:
        #                 - /var/run/docker.sock:/var/run/docker.sock
